/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DavaButton {
        "active": boolean;
        "appearance": 'default' | 'outline';
        "disabled": boolean;
    }
    interface DavaButtonGroup {
    }
}
declare global {
    interface HTMLDavaButtonElement extends Components.DavaButton, HTMLStencilElement {
    }
    var HTMLDavaButtonElement: {
        prototype: HTMLDavaButtonElement;
        new (): HTMLDavaButtonElement;
    };
    interface HTMLDavaButtonGroupElement extends Components.DavaButtonGroup, HTMLStencilElement {
    }
    var HTMLDavaButtonGroupElement: {
        prototype: HTMLDavaButtonGroupElement;
        new (): HTMLDavaButtonGroupElement;
    };
    interface HTMLElementTagNameMap {
        "dava-button": HTMLDavaButtonElement;
        "dava-button-group": HTMLDavaButtonGroupElement;
    }
}
declare namespace LocalJSX {
    interface DavaButton {
        "active"?: boolean;
        "appearance"?: 'default' | 'outline';
        "disabled"?: boolean;
        "onDavaBlur"?: (event: CustomEvent<any>) => void;
        "onDavaClick"?: (event: CustomEvent<any>) => void;
        "onDavaFocus"?: (event: CustomEvent<any>) => void;
    }
    interface DavaButtonGroup {
        "onDavaChange"?: (event: CustomEvent<HTMLDavaButtonElement>) => void;
    }
    interface IntrinsicElements {
        "dava-button": DavaButton;
        "dava-button-group": DavaButtonGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dava-button": LocalJSX.DavaButton & JSXBase.HTMLAttributes<HTMLDavaButtonElement>;
            "dava-button-group": LocalJSX.DavaButtonGroup & JSXBase.HTMLAttributes<HTMLDavaButtonGroupElement>;
        }
    }
}
